services:
  pazyr_discovery_engine:
    profiles: ["v1-uat"]
    volumes:
      - ./volumes/data:/data
    networks:
      - data-network

  knowledge_builder:
    profiles: ["v1-dev"]
    volumes:
      - ./volumes/data:/data

  redis:
    profiles: ["infra"]

  weaviate:
    profiles: ["infra"]

  postgres:
    profiles: ["infra"]

networks:
  coe-network:
    external: true
  data-network:
    external: true