[project]
name = "pazyr-knowledge-builder"
version = "0.1.0"
description = "Knowledge Builder service for Pazyr"
readme = "README.md"
requires-python = ">=3.13"
authors= [
    { name = "Pazye Team" }
]

dependencies = [
  "pazyr_core>=0.1.0",
  "ollama>=0.6.1",
  "pyyaml>=6.0.3",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["knowledge_builder"]
package-dir = {"" = "src"}